In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

## Create & Read

#### 1D Array

In [12]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [10]:
arr1.size

5

In [13]:
arr1.size

6

#### 2D array

In [21]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])

In [15]:
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [16]:
arr2.ndim

2

In [18]:
arr2.shape #(rows, columns)

(2, 3)

In [19]:
arr2.dtype

dtype('int64')

In [20]:
arr2.size

6

#### 3D array

In [27]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])

In [28]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [29]:
arr3.ndim

3

In [30]:
arr3.shape

(3, 2, 3)

In [31]:
arr3.size

18

## Create Random array

In [32]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.06977597, 0.37712211, 0.08721546],
        [0.9989518 , 0.25445137, 0.98114517]],

       [[0.60595952, 0.20083667, 0.33318141],
        [0.03488901, 0.08283915, 0.9059484 ]],

       [[0.4666859 , 0.41175806, 0.66626753],
        [0.48484596, 0.80452679, 0.10435099]]])

In [33]:
randomArr.shape

(3, 2, 3)

In [34]:
randomArr.dtype

dtype('float64')

In [35]:
randomArr.size

18

In [36]:
zeros = np.zeros((3, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
zeros.ndim

3

In [39]:
full = np.full((3, 2, 3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [40]:
ones = np.ones((2, 2))
ones

array([[1., 1.],
       [1., 1.]])

In [41]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [42]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [43]:
arr3[0, 1]

array([6, 7, 4])

In [44]:
arr3[0, 1, 1]

np.int64(7)

In [45]:
arr3[0: 2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [47]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [48]:
arr3[1, 0, 1]

np.int64(5)

In [49]:
arr3[1][0][1]

np.int64(5)

### Update & Delete

In [50]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [51]:
a1

array([[[0.33949023, 0.11742773],
        [0.70357939, 0.64994229],
        [0.2912388 , 0.31015304]],

       [[0.57533326, 0.75592655],
        [0.63505363, 0.64352325],
        [0.74728471, 0.22923147]]])

In [52]:
a2

array([[[0.23611764, 0.80967133],
        [0.01564801, 0.97559974],
        [0.60848024, 0.53157931]],

       [[0.92383299, 0.10941249],
        [0.47645036, 0.11735604],
        [0.1903713 , 0.54345025]]])

#### Basic Math Operations

In [54]:
np.add(a1, a2)

array([[[0.57560787, 0.92709906],
        [0.7192274 , 1.62554204],
        [0.89971903, 0.84173235]],

       [[1.49916626, 0.86533905],
        [1.11150399, 0.76087929],
        [0.93765601, 0.77268172]]])

In [55]:
np.subtract(a1, a2)

array([[[ 0.10337259, -0.69224359],
        [ 0.68793138, -0.32565745],
        [-0.31724144, -0.22142627]],

       [[-0.34849973,  0.64651406],
        [ 0.15860326,  0.52616721],
        [ 0.55691341, -0.31421878]]])

In [56]:
np.divide(a1, a2)

array([[[ 1.43780123,  0.14503136],
        [44.96286431,  0.66619769],
        [ 0.47863313,  0.58345581]],

       [[ 0.6227676 ,  6.90896019],
        [ 1.33288518,  5.48351179],
        [ 3.92540628,  0.42180765]]])

In [58]:
np.multiply(a1, a2)

array([[[0.08015963, 0.09507787],
        [0.01100962, 0.63408354],
        [0.17721305, 0.16487094]],

       [[0.53151185, 0.08270781],
        [0.30257153, 0.07552134],
        [0.14226156, 0.1245759 ]]])

#### Update

In [59]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [60]:
arr3[0, 0, 2] = 500

In [61]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [62]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

#### Reshape

In [64]:
arr3.shape

(3, 2, 3)

In [65]:
arr3_reshape = arr3.reshape((2, 3, 3))

In [66]:
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

#### Append & Insert

In [67]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
new_arr = np.ones((3, 2, 3))
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
append = np.append(zeros, new_arr, axis=0) #axis 0-> row, 1-> column

In [70]:
append

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [71]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [73]:
inserted_arr = np.insert(zeros, 1, new_arr, axis=0)
inserted_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
arr5 = np.random.rand(3, 2, 3)

In [75]:
arr5

array([[[0.14779045, 0.69975584, 0.55162912],
        [0.43561784, 0.43992812, 0.65471513]],

       [[0.90813971, 0.94975683, 0.42312846],
        [0.88945266, 0.95975446, 0.25507114]],

       [[0.45796139, 0.96605884, 0.34860842],
        [0.67175033, 0.29529086, 0.25823814]]])

In [76]:
arr6 = np.delete(arr5, 0, axis=1)

In [77]:
arr6

array([[[0.43561784, 0.43992812, 0.65471513]],

       [[0.88945266, 0.95975446, 0.25507114]],

       [[0.67175033, 0.29529086, 0.25823814]]])

In [78]:
np.save("new_array", arr6)

In [79]:
np.load("new_array.npy")

array([[[0.43561784, 0.43992812, 0.65471513]],

       [[0.88945266, 0.95975446, 0.25507114]],

       [[0.67175033, 0.29529086, 0.25823814]]])